Source secrets in pipeline where needed.

diff --git a/.github/workflows/deploy-webapp.yaml b/.github/workflows/deploy-webapp.yaml
--- a/.github/workflows/deploy-webapp.yaml
+++ b/.github/workflows/deploy-webapp.yaml
@@ -26,6 +26,15 @@ jobs:
         env:
           GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}
 
+      - name: "Source environment variables"
+        run: |
+          if [ -f ./deploy/secrets/webapp-secrets.sh ]; then
+            source ./deploy/secrets/webapp-secrets.sh
+          else
+            echo "webapp-secrets.sh not found!"
+            exit 1
+          fi
+
       - name: Setup Kubernetes configuration
         uses: azure/k8s-set-context@v3
         with:
@@ -53,14 +62,13 @@ jobs:
             latest
 
       - name: Build and push Docker image
-        run: |
-          source ./deploy/secrets/webapp-secrets.sh
-          docker buildx build \
-            --push \
-            --file ./webapp/Dockerfile \
-            --tag ${{ steps.meta.outputs.tags }} \
-            --label ${{ steps.meta.outputs.labels }} \
-            ./webapp
+        uses: docker/build-push-action@v5
+        with:
+          context: ./webapp
+          file: ./webapp/Dockerfile
+          push: true
+          tags: ${{ steps.meta.outputs.tags }}
+          labels: ${{ steps.meta.outputs.labels }}
 
       - name: Setup Helm
         uses: azure/setup-helm@v3
